remote_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTDjitOlmILea7koCORJkq6QrUcwBJM7K3vy4guXB0mU_nWR6wsPn136bpH6ykoUxyYMW7wTwkzE37l/pub?output=csv'
proj_dir: 'C:\Users\Owner\Documents\305 Python\Lab 1A\WestNileOutbreak\'
data_format: 'GSheet'
geocode_prefix_url: 'https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address='
geocode_suffix_url: '&benchmark=2020&format=json'
